[VCDA-3441] Implement RDE upgrade logic during CSI start up
vmware/cloud-director-named-disk-csi-driver pull request #55
Opened 2022-05-24 22:20 UTC by ymo24

* Created ENV `UPGRADE_RDE` and flag parameter `--upgrade-rde string               CSI upgrade rde`
* Get persistentVolumes list from old RDE and wipe off section `persistentVolumes`
* Add Todo comments on several places. We should record errors in `status.csi.errors` in a separate PR
* Passed the Testing
Signed-off-by: ymo24 <ymo@vmware.com>

2022-05-25 02:19 UTC, arunmk requested changes
> Reviewed 3 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/55)* status: 3 of 6 files reviewed, 4 unresolved discussions (waiting on @Anirudh9794, @sahithi, and @ymo24)

___
*[`pkg/csi/driver.go` line 115 at r1](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/55#-N2srno55fbvY_8TKMXs:-N2srno55fbvY_8TKMXt:b-vepx6c) ([raw file](https://github.com/vmware/cloud-director-named-disk-csi-driver/blob/d600c4873138fec92d44eed883f9401b8833cba1/pkg/csi/driver.go#L115)):*
> ```Go
> 	d.cs = NewControllerService(d, diskManager.VCDClient, diskManager.ClusterID, VAppName)
> 	d.ids = NewIdentityServer(d)
> 	if upgradeRde == "true" {
> ```

Nit: usually for code with complex paths like this, it is useful to return early. The idea is to reduce the number of nested `if`s as much as possible. For example:
```
if upgradeRde != "true" {
	return
}

if !util.IsValidEntityId(diskManager.ClusterID) {
	return
}

err := diskManager.UpdatePvRDE()
if err != nil {
	klog.Infof(err.Error())
}

```
___
*[`pkg/util/defined_entity_util.go` line 16 at r1](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/55#-N2sydKxBGNZ9yWPXe-3:-N2sydKxBGNZ9yWPXe-4:bpkdte7) ([raw file](https://github.com/vmware/cloud-director-named-disk-csi-driver/blob/d600c4873138fec92d44eed883f9401b8833cba1/pkg/util/defined_entity_util.go#L16)):*
> ```Go
> 
> func IsValidEntityId(rdeId string) bool {
> 	if rdeId == "" || strings.HasPrefix(rdeId, vcdsdk.NoRdePrefix) {
> ```

we can just do:
```
    return rdeId != "" && !strings.HasPrefix(rdeId, vcdsdk.NoRdePrefix)
```
___
*[`pkg/util/defined_entity_util.go` line 112 at r1](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/55#-N2sz5r74mnYC8kc5Zh4:-N2sz5r74mnYC8kc5Zh5:byic2s5) ([raw file](https://github.com/vmware/cloud-director-named-disk-csi-driver/blob/d600c4873138fec92d44eed883f9401b8833cba1/pkg/util/defined_entity_util.go#L112)):*
> ```Go
> 	pvInterfacesSlice, ok := pvInterfaces.([]interface{})
> 	if !ok {
> 		return nil, nil, fmt.Errorf("unable to convert [%T] to slice of interface", pvInterfaces)
> ```

it can be `to []interface{}` so that the log is specific and clear
___
*[`pkg/vcdcsiclient/disks.go` line 596 at r1](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/55#-N2szdWl7A7bkwip1OTd:-N2szdWl7A7bkwip1OTe:b-s1z8tm) ([raw file](https://github.com/vmware/cloud-director-named-disk-csi-driver/blob/d600c4873138fec92d44eed883f9401b8833cba1/pkg/vcdcsiclient/disks.go#L596)):*
> ```Go
> }
> 
> func (diskManager *DiskManager) upgradeRDEPersistentVolumes(etag string,
> ```

This is problematic as it will lead to data loss. What is done here is this:
1. get the list of PV
2. upgradeRDEPersistentVolumes and remove the disk list from RDE (in VCD)
3. get the PV details
4. update RDE in VCD with PV details

What happens if the operation fails (someone kills CSI) between 2 and 4? VCD has the empty PV and all of the PV details are in memory of the crashed process.

What we should do is this:
a. get list of PV
b. get PV details
c. update local RDE data structure where we remove oldPVs and add newPVs
d. perform one update to RDE in VCD

So the above is a transactional unit update and will update both. The whole a-d must be encapsulated into a loop with etag checks, so that we can retry in case of collisions. 


<!-- Sent from Reviewable.io -->

2022-05-25 16:24 UTC, sahithi requested changes
> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/55)* status: all files reviewed, 13 unresolved discussions (waiting on @Anirudh9794, @arunmk, and @ymo24)

___
*[`pkg/csi/driver.go` line 121 at r1](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/55#-N2vZMIt7MwBPVZFXHQk:-N2vZMIt7MwBPVZFXHQl:b90we64) ([raw file](https://github.com/vmware/cloud-director-named-disk-csi-driver/blob/d600c4873138fec92d44eed883f9401b8833cba1/pkg/csi/driver.go#L121)):*
> ```Go
> 				klog.Infof(err.Error())
> 			}
> 		}
> ```

Please add a log statement here that upgrade is skipped because rdeId is empty or not valid.
___
*[`pkg/util/defined_entity_util.go` line 15 at r1](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/55#-N2vYlNc7j7ESoNgxCzB:-N2vYlNc7j7ESoNgxCzC:b-cud14b) ([raw file](https://github.com/vmware/cloud-director-named-disk-csi-driver/blob/d600c4873138fec92d44eed883f9401b8833cba1/pkg/util/defined_entity_util.go#L15)):*
> ```Go
> )
> 
> func IsValidEntityId(rdeId string) bool {
> ```

Please move this utils method to CPI common library. 
___
*[`pkg/util/defined_entity_util.go` line 91 at r1](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/55#-N2vblCyEBdLoFZa6_y8:-N2vblCyEBdLoFZa6_y9:bogf6xy) ([raw file](https://github.com/vmware/cloud-director-named-disk-csi-driver/blob/d600c4873138fec92d44eed883f9401b8833cba1/pkg/util/defined_entity_util.go#L91)):*
> ```Go
> }
> 
> func GetOldPVsFromRDE(rde *swaggerClient.DefinedEntity) (*swaggerClient.DefinedEntity, []string, error) {
> ```

Please fix all the log statements to hold rdeId and make them elaborate.
___
*[`pkg/util/defined_entity_util.go` line 94 at r1](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/55#-N2vbsQjD47b8yj9C_US:-N2vbsQjD47b8yj9C_UT:b6u0xyp) ([raw file](https://github.com/vmware/cloud-director-named-disk-csi-driver/blob/d600c4873138fec92d44eed883f9401b8833cba1/pkg/util/defined_entity_util.go#L94)):*
> ```Go
> 	statusEntry, ok := rde.Entity["status"]
> 	if !ok {
> 		return nil, nil, fmt.Errorf("could not find 'status' entry in defined entity")
> ```

nit: 'status' entry -> 'status" key
___
*[`pkg/util/defined_entity_util.go` line 104 at r1](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/55#-N2vbwGA7AKgDrbeT2ts:-N2vbwGA7AKgDrbeT2tt:b-7fyho1) ([raw file](https://github.com/vmware/cloud-director-named-disk-csi-driver/blob/d600c4873138fec92d44eed883f9401b8833cba1/pkg/util/defined_entity_util.go#L104)):*
> ```Go
> 
> 	if !ok {
> 		return nil, make([]string, 0), fmt.Errorf("no entity [%s] found", OldPersistentVolumeKey)
> ```

something like - persistentVolume Key not found in the status section of the rde with Id of so and so version.
___
*[`pkg/util/defined_entity_util.go` line 123 at r1](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/55#-N2v_UDv4MCyBKNqejhm:-N2v_UDv4MCyBKNqejhn:b6t5b3c) ([raw file](https://github.com/vmware/cloud-director-named-disk-csi-driver/blob/d600c4873138fec92d44eed883f9401b8833cba1/pkg/util/defined_entity_util.go#L123)):*
> ```Go
> 	}
> 
> 	delete(statusMap, OldPersistentVolumeKey)
> ```

delete needs to be done after entries have been added to the new format (csi section). 

Something to keep in mind in general: Method name must reflect the exact operation it does inside. currently, the method name suggests a GET content operation and internally we are doing some silent DELETE content. 
___
*[`pkg/vcdcsiclient/disks.go` line 209 at r1](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/55#-N2vdBG1CCA0_Z7BTSHc:-N2vdBG1CCA0_Z7BTSHd:benikp2) ([raw file](https://github.com/vmware/cloud-director-named-disk-csi-driver/blob/d600c4873138fec92d44eed883f9401b8833cba1/pkg/vcdcsiclient/disks.go#L209)):*
> ```Go
> 
> func (diskManager *DiskManager) govcdGetDiskById(diskId string, refresh bool) (*vcdtypes.Disk, error) {
> 	klog.Infof("Entered GetDiskByName for id [%s]", diskId)
> ```

please remove this log statement or change it to "retrieving disk by Id"
Also, increment the log verbosity level for the util methods. Please use your judgment while incrementing the log level.
___
*[`pkg/vcdcsiclient/disks.go` line 213 at r1](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/55#-N2w-bIrDJveN_F8qgEA:-N2w-bIrDJveN_F8qgEB:b-6nl7ri) ([raw file](https://github.com/vmware/cloud-director-named-disk-csi-driver/blob/d600c4873138fec92d44eed883f9401b8833cba1/pkg/vcdcsiclient/disks.go#L213)):*
> ```Go
> 		err := diskManager.VCDClient.VDC.Refresh()
> 		if err != nil {
> 			return nil, fmt.Errorf("disk name should not be empty")
> ```

You mean vdc details are insufficient?
___
*[`pkg/vcdcsiclient/disks.go` line 596 at r1](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/55#-N2szdWl7A7bkwip1OTd:-N2w0pFh8i5VgNwyuvIt:b32v57) ([raw file](https://github.com/vmware/cloud-director-named-disk-csi-driver/blob/d600c4873138fec92d44eed883f9401b8833cba1/pkg/vcdcsiclient/disks.go#L596)):*
<details><summary><i>Previously, arunmk (Arun M. Krishnakumar) wrote…</i></summary><blockquote>

This is problematic as it will lead to data loss. What is done here is this:
1. get the list of PV
2. upgradeRDEPersistentVolumes and remove the disk list from RDE (in VCD)
3. get the PV details
4. update RDE in VCD with PV details

What happens if the operation fails (someone kills CSI) between 2 and 4? VCD has the empty PV and all of the PV details are in memory of the crashed process.

What we should do is this:
a. get list of PV
b. get PV details
c. update local RDE data structure where we remove oldPVs and add newPVs
d. perform one update to RDE in VCD

So the above is a transactional unit update and will update both. The whole a-d must be encapsulated into a loop with etag checks, so that we can retry in case of collisions. 
</blockquote></details>

+1
___
*[`pkg/vcdcsiclient/disks.go` line 701 at r1](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/55#-N2w18cb7XSzr5QYdlrx:-N2w18cb7XSzr5QYdlry:b-9frq35) ([raw file](https://github.com/vmware/cloud-director-named-disk-csi-driver/blob/d600c4873138fec92d44eed883f9401b8833cba1/pkg/vcdcsiclient/disks.go#L701)):*
> ```Go
> }
> 
> func (diskManager *DiskManager) UpdatePvRDE() error {
> ```

This logic needs to be redone


<!-- Sent from Reviewable.io -->

2022-05-25 21:43 UTC, ymo24 reviewed
> *[Reviewable](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/55)* status: 2 of 6 files reviewed, 16 unresolved discussions (waiting on @Anirudh9794, @arunmk, and @sahithi)

___
*[`pkg/csi/driver.go` line 121 at r1](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/55#-N2vZMIt7MwBPVZFXHQk:-N2x7H_30HkPtMuJO7sK:b-d5aw97) ([raw file](https://github.com/vmware/cloud-director-named-disk-csi-driver/blob/d600c4873138fec92d44eed883f9401b8833cba1/pkg/csi/driver.go#L121)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

Please add a log statement here that upgrade is skipped because rdeId is empty or not valid.
</blockquote></details>

Already add two logs to handle the flag command error and rde id invalid error. Thanks, Sahithi.
___
*[`pkg/util/defined_entity_util.go` line 15 at r1](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/55#-N2vYlNc7j7ESoNgxCzB:-N2wQrGkCRCw6OkQEA2E:b-ngapw6) ([raw file](https://github.com/vmware/cloud-director-named-disk-csi-driver/blob/d600c4873138fec92d44eed883f9401b8833cba1/pkg/util/defined_entity_util.go#L15)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

Please move this utils method to CPI common library. 
</blockquote></details>

Yes, I would take another PR to do this.
___
*[`pkg/util/defined_entity_util.go` line 16 at r1](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/55#-N2sydKxBGNZ9yWPXe-3:-N2x7C6eE35WojO9aAkd:b-2z3h0m) ([raw file](https://github.com/vmware/cloud-director-named-disk-csi-driver/blob/d600c4873138fec92d44eed883f9401b8833cba1/pkg/util/defined_entity_util.go#L16)):*
<details><summary><i>Previously, arunmk (Arun M. Krishnakumar) wrote…</i></summary><blockquote>

we can just do:
```
    return rdeId != "" && !strings.HasPrefix(rdeId, vcdsdk.NoRdePrefix)
```


</blockquote></details>

Already did that. Thanks Arun
___
*[`pkg/util/defined_entity_util.go` line 91 at r1](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/55#-N2vblCyEBdLoFZa6_y8:-N2x7oYV1CvW5PrX5OHV:bju2pnb) ([raw file](https://github.com/vmware/cloud-director-named-disk-csi-driver/blob/d600c4873138fec92d44eed883f9401b8833cba1/pkg/util/defined_entity_util.go#L91)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

Please fix all the log statements to hold rdeId and make them elaborate.
</blockquote></details>

I already add redId as the parameter into this function
___
*[`pkg/util/defined_entity_util.go` line 94 at r1](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/55#-N2vbsQjD47b8yj9C_US:-N2w_DD094GD6pkEZtD3:b8pjanj) ([raw file](https://github.com/vmware/cloud-director-named-disk-csi-driver/blob/d600c4873138fec92d44eed883f9401b8833cba1/pkg/util/defined_entity_util.go#L94)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

nit: 'status' entry -> 'status" key
</blockquote></details>

Already done. Thanks Sahithi! 
___
*[`pkg/util/defined_entity_util.go` line 104 at r1](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/55#-N2vbwGA7AKgDrbeT2ts:-N2xAC-S6sFUfUUKUrlD:b-896fix) ([raw file](https://github.com/vmware/cloud-director-named-disk-csi-driver/blob/d600c4873138fec92d44eed883f9401b8833cba1/pkg/util/defined_entity_util.go#L104)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

something like - persistentVolume Key not found in the status section of the rde with Id of so and so version.
</blockquote></details>

Done.
___
*[`pkg/util/defined_entity_util.go` line 112 at r1](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/55#-N2sz5r74mnYC8kc5Zh4:-N2xACkM8t4vjkgHI3-A:b-896fix) ([raw file](https://github.com/vmware/cloud-director-named-disk-csi-driver/blob/d600c4873138fec92d44eed883f9401b8833cba1/pkg/util/defined_entity_util.go#L112)):*
<details><summary><i>Previously, arunmk (Arun M. Krishnakumar) wrote…</i></summary><blockquote>

it can be `to []interface{}` so that the log is specific and clear
</blockquote></details>

Done.
___
*[`pkg/util/defined_entity_util.go` line 123 at r1](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/55#-N2v_UDv4MCyBKNqejhm:-N2x7xUp8LrTlr6etgjZ:bxx2b7r) ([raw file](https://github.com/vmware/cloud-director-named-disk-csi-driver/blob/d600c4873138fec92d44eed883f9401b8833cba1/pkg/util/defined_entity_util.go#L123)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

delete needs to be done after entries have been added to the new format (csi section). 

Something to keep in mind in general: Method name must reflect the exact operation it does inside. currently, the method name suggests a GET content operation and internally we are doing some silent DELETE content. 
</blockquote></details>

I changed the name to `UpgradePVResourceToRDE`. It's used to update local resourceSet section.
___
*[`pkg/vcdcsiclient/disks.go` line 209 at r1](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/55#-N2vdBG1CCA0_Z7BTSHc:-N2x8G4s4SPurTvATXxw:b-896fix) ([raw file](https://github.com/vmware/cloud-director-named-disk-csi-driver/blob/d600c4873138fec92d44eed883f9401b8833cba1/pkg/vcdcsiclient/disks.go#L209)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

please remove this log statement or change it to "retrieving disk by Id"
Also, increment the log verbosity level for the util methods. Please use your judgment while incrementing the log level.
</blockquote></details>

Done.
___
*[`pkg/vcdcsiclient/disks.go` line 213 at r1](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/55#-N2w-bIrDJveN_F8qgEA:-N2x5IEv4hcyRpQK_dct:bcg92ai) ([raw file](https://github.com/vmware/cloud-director-named-disk-csi-driver/blob/d600c4873138fec92d44eed883f9401b8833cba1/pkg/vcdcsiclient/disks.go#L213)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

You mean vdc details are insufficient?
</blockquote></details>

I changed it to fmt.Errorf("error when refreshing by disk id %s, [%v]", diskId, err) to elaborate the err.
___
*[`pkg/vcdcsiclient/disks.go` line 596 at r1](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/55#-N2szdWl7A7bkwip1OTd:-N2x8H_Q8yrIV8G9BSzo:b-sqyiq0) ([raw file](https://github.com/vmware/cloud-director-named-disk-csi-driver/blob/d600c4873138fec92d44eed883f9401b8833cba1/pkg/vcdcsiclient/disks.go#L596)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

+1
</blockquote></details>

I moved the whole transaction unit to the below.
___
*[`pkg/vcdcsiclient/disks.go` line 701 at r1](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/55#-N2w18cb7XSzr5QYdlrx:-N2x8UiG8H04_TiUrmdk:b-896fix) ([raw file](https://github.com/vmware/cloud-director-named-disk-csi-driver/blob/d600c4873138fec92d44eed883f9401b8833cba1/pkg/vcdcsiclient/disks.go#L701)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

This logic needs to be redone
</blockquote></details>

Done.
___
*[`pkg/vcdcsiclient/disks.go` line 699 at r2](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/55#-N2x8ZHo4jZedBFE14lB:-N2x8ZHo4jZedBFE14lC:b9i76g7) ([raw file](https://github.com/vmware/cloud-director-named-disk-csi-driver/blob/0ea3e132db1eaed22bc3fad2618e0172553c9760/pkg/vcdcsiclient/disks.go#L699)):*
> a. get list of PV
___
*[`pkg/vcdcsiclient/disks.go` line 705 at r2](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/55#-N2x8dzDCjzZyapEN0yk:-N2x8dzDCjzZyapEN0yl:bf4uai3) ([raw file](https://github.com/vmware/cloud-director-named-disk-csi-driver/blob/0ea3e132db1eaed22bc3fad2618e0172553c9760/pkg/vcdcsiclient/disks.go#L705)) [...]

2022-05-25 23:28 UTC, ymo24 reviewed
> *[Reviewable](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/55)* status: 2 of 6 files reviewed, 17 unresolved discussions (waiting on @Anirudh9794, @arunmk, and @sahithi)

___
*[`pkg/vcdcsiclient/disks.go` line 724 at r3](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/55#-N2xXjED9QhhoS4RO59A:-N2xXjED9QhhoS4RO59B:bhele2x) ([raw file](https://github.com/vmware/cloud-director-named-disk-csi-driver/blob/3d46f893b0208e4a0ea203a2ca9884aafc69ff92/pkg/vcdcsiclient/disks.go#L724)):*
> ```Go
> 		delete(updatedMap, util.OldPersistentVolumeKey)
> 		rde.Entity["status"] = updatedMap
> 		_, httpResponse, err := diskManager.VCDClient.APIClient.DefinedEntityApi.UpdateDefinedEntity(context.Background(), rde, etag, diskManager.ClusterID, nil)
> ```

d update RDE in VCD with PV details


<!-- Sent from Reviewable.io -->

2022-05-26 00:48 UTC, Anirudh9794 reviewed
> Reviewed 2 of 6 files at r1, 1 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/55)* status: 3 of 6 files reviewed, 24 unresolved discussions (waiting on @arunmk, @sahithi, and @ymo24)

___
*[`cmd/csi/main.go` line 75 at r3](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/55#-N2xfaSL4haw6GPCu6u9:-N2xfaSL4haw6GPCu6uA:b3edwnz) ([raw file](https://github.com/vmware/cloud-director-named-disk-csi-driver/blob/3d46f893b0208e4a0ea203a2ca9884aafc69ff92/cmd/csi/main.go#L75)):*
> ```Go
> 	cmd.PersistentFlags().StringVar(&nodeIDFlag, "nodeid", "", "node id")
> 
> 	cmd.PersistentFlags().StringVar(&upgradeRDEFlag, "upgrade-rde", "", "CSI upgrade rde")
> ```

Like the idea of adding a flag to distinguish between node plugin and csi controller.
Please add a comment to indicate why the flag is needed.
___
*[`cmd/csi/main.go` line 77 at r3](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/55#-N2xheWf18XGM86YHMvq:-N2xheWf18XGM86YHMvr:boc2nqs) ([raw file](https://github.com/vmware/cloud-director-named-disk-csi-driver/blob/3d46f893b0208e4a0ea203a2ca9884aafc69ff92/cmd/csi/main.go#L77)):*
> ```Go
> 	cmd.PersistentFlags().StringVar(&upgradeRDEFlag, "upgrade-rde", "", "CSI upgrade rde")
> 
> 	cmd.PersistentFlags().StringVar(&endpointFlag, "endpoint", "", "CSI endpoint")
> ```

I also see a `cmd.PersistentFlags().BoolVar()` is it possible to use that?
___
*[`manifests/csi-controller.yaml` line 148 at r3](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/55#-N2xi6271bzD-xp8nYvR:-N2xi6271bzD-xp8nYvS:bn84uxs) ([raw file](https://github.com/vmware/cloud-director-named-disk-csi-driver/blob/3d46f893b0208e4a0ea203a2ca9884aafc69ff92/manifests/csi-controller.yaml#L148)):*
> ```YAML
>             - --cloud-config=/etc/kubernetes/vcloud/vcloud-csi-config.yaml
>             - --endpoint=$(CSI_ENDPOINT)
>             - --upgrade-rde=$(UPGRADE_RDE)
> ```

I think it is also a good idea to rename the flag to something like  `run-as-controller` or `csi-controller`

Can we also make the option a flag? so that we can avoid adding an environment variable below.
___
*[`pkg/csi/driver.go` line 116 at r3](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/55#-N2xeLnhAn3KP0xwYcEb:-N2xeLnhAn3KP0xwYcEc:b-endzn) ([raw file](https://github.com/vmware/cloud-director-named-disk-csi-driver/blob/3d46f893b0208e4a0ea203a2ca9884aafc69ff92/pkg/csi/driver.go#L116)):*
> ```Go
> 	d.ids = NewIdentityServer(d)
> 	if upgradeRde != "true" {
> 		klog.Infof("upgradeRde flag is not valid: [%s]", upgradeRde)
> ```

klog.Infof("Skipping RDE CSI section upgrade") or something similar.
___
*[`pkg/csi/driver.go` line 122 at r3](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/55#-N2xdEXa7Fh-zSAOnNBY:-N2xdEXa7Fh-zSAOnNBZ:bcxpxmz) ([raw file](https://github.com/vmware/cloud-director-named-disk-csi-driver/blob/3d46f893b0208e4a0ea203a2ca9884aafc69ff92/pkg/csi/driver.go#L122)):*
> ```Go
> 		klog.Infof("upgrade RDE is skipped as invalid RDE: [%s]", diskManager.ClusterID)
> 		return
> 	}
> ```

Please add another check here to not upgrade CSI status section for nativeCluster RDEs
___
*[`pkg/csi/driver.go` line 125 at r3](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/55#-N2xp1kvCGE5erNOSxmO:-N2xp1kvCGE5erNOSxmP:b6a0icc) ([raw file](https://github.com/vmware/cloud-director-named-disk-csi-driver/blob/3d46f893b0208e4a0ea203a2ca9884aafc69ff92/pkg/csi/driver.go#L125)):*
> ```Go
> 	err := diskManager.UpgradeRDEPersistentVolumes()
> 	if err != nil {
> 		klog.Infof(err.Error())
> ```

If the RDE is of entityType capvcdCluster and CSI status section upgrade fails, i think there should be a hard failure.
___
*[`pkg/vcdcsiclient/disks.go` line 684 at r3](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/55#-N2xaljZ67hxJ4Ur9nc2:-N2xaljZ67hxJ4Ur9nc3:bw9tjp0) ([raw file](https://github.com/vmware/cloud-director-named-disk-csi-driver/blob/3d46f893b0208e4a0ea203a2ca9884aafc69ff92/pkg/vcdcsiclient/disks.go#L684)):*
> ```Go
> }
> 
> func (diskManager *DiskManager) UpgradeRDEPersistentVolumes() error {
> ```

Please add a comment here to indicate that the function needs to be executed for only capvcdCluster RDEs


<!-- Sent from Reviewable.io -->

2022-05-26 18:39 UTC, ymo24 reviewed
> *[Reviewable](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/55)* status: 3 of 6 files reviewed, 25 unresolved discussions (waiting on @Anirudh9794, @arunmk, and @sahithi)

___
*[`cmd/csi/main.go` line 75 at r3](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/55#-N2xfaSL4haw6GPCu6u9:-N30FBBjCwDLLTxkF0Dw:b-896fix) ([raw file](https://github.com/vmware/cloud-director-named-disk-csi-driver/blob/3d46f893b0208e4a0ea203a2ca9884aafc69ff92/cmd/csi/main.go#L75)):*
<details><summary><i>Previously, Anirudh9794 wrote…</i></summary><blockquote>

Like the idea of adding a flag to distinguish between node plugin and csi controller.
Please add a comment to indicate why the flag is needed.
</blockquote></details>

Done.
___
*[`cmd/csi/main.go` line 77 at r3](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/55#-N2xheWf18XGM86YHMvq:-N30FBxwDXMjua57eXHU:b-896fix) ([raw file](https://github.com/vmware/cloud-director-named-disk-csi-driver/blob/3d46f893b0208e4a0ea203a2ca9884aafc69ff92/cmd/csi/main.go#L77)):*
<details><summary><i>Previously, Anirudh9794 wrote…</i></summary><blockquote>

I also see a `cmd.PersistentFlags().BoolVar()` is it possible to use that?
</blockquote></details>

Done.
___
*[`manifests/csi-controller.yaml` line 148 at r3](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/55#-N2xi6271bzD-xp8nYvR:-N30FCgqB8UFkRMn6TzO:b-896fix) ([raw file](https://github.com/vmware/cloud-director-named-disk-csi-driver/blob/3d46f893b0208e4a0ea203a2ca9884aafc69ff92/manifests/csi-controller.yaml#L148)):*
<details><summary><i>Previously, Anirudh9794 wrote…</i></summary><blockquote>

I think it is also a good idea to rename the flag to something like  `run-as-controller` or `csi-controller`

Can we also make the option a flag? so that we can avoid adding an environment variable below.
</blockquote></details>

Done.
___
*[`pkg/csi/driver.go` line 118 at r1](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/55#-N2xuaELDMrgwr5k8ayc:-N2xuaEM8PO_QFyuHCnF:b-fcywnd) ([raw file](https://github.com/vmware/cloud-director-named-disk-csi-driver/blob/d600c4873138fec92d44eed883f9401b8833cba1/pkg/csi/driver.go#L118)):*
> cmd.PersistentFlags(
___
*[`pkg/csi/driver.go` line 116 at r3](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/55#-N2xeLnhAn3KP0xwYcEb:-N30FDg7EOTm4KBU19EN:b-896fix) ([raw file](https://github.com/vmware/cloud-director-named-disk-csi-driver/blob/3d46f893b0208e4a0ea203a2ca9884aafc69ff92/pkg/csi/driver.go#L116)):*
<details><summary><i>Previously, Anirudh9794 wrote…</i></summary><blockquote>

klog.Infof("Skipping RDE CSI section upgrade") or something similar.
</blockquote></details>

Done.
___
*[`pkg/csi/driver.go` line 122 at r3](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/55#-N2xdEXa7Fh-zSAOnNBY:-N30cSGp0y-eeXodWkGM:b-896fix) ([raw file](https://github.com/vmware/cloud-director-named-disk-csi-driver/blob/3d46f893b0208e4a0ea203a2ca9884aafc69ff92/pkg/csi/driver.go#L122)):*
<details><summary><i>Previously, Anirudh9794 wrote…</i></summary><blockquote>

Please add another check here to not upgrade CSI status section for nativeCluster RDEs
</blockquote></details>

Done.
___
*[`pkg/csi/driver.go` line 125 at r3](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/55#-N2xp1kvCGE5erNOSxmO:-N30cSbw3CLybIODab0J:b-896fix) ([raw file](https://github.com/vmware/cloud-director-named-disk-csi-driver/blob/3d46f893b0208e4a0ea203a2ca9884aafc69ff92/pkg/csi/driver.go#L125)):*
<details><summary><i>Previously, Anirudh9794 wrote…</i></summary><blockquote>

If the RDE is of entityType capvcdCluster and CSI status section upgrade fails, i think there should be a hard failure.
</blockquote></details>

Done.
___
*[`pkg/vcdcsiclient/disks.go` line 684 at r3](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/55#-N2xaljZ67hxJ4Ur9nc2:-N30eeal55L7sbu6rjJr:b-896fix) ([raw file](https://github.com/vmware/cloud-director-named-disk-csi-driver/blob/3d46f893b0208e4a0ea203a2ca9884aafc69ff92/pkg/vcdcsiclient/disks.go#L684)):*
<details><summary><i>Previously, Anirudh9794 wrote…</i></summary><blockquote>

Please add a comment here to indicate that the function needs to be executed for only capvcdCluster RDEs
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-05-26 22:01 UTC, sahithi approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> few minor comments

> *[Reviewable](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/55#-:-N31MaiLEeFNCtCMldnq:b-ha9yve)* status: 0 of 11 files reviewed, 22 unresolved discussions (waiting on @Anirudh9794, @arunmk, @sahithi, and @ymo24)

___
*[`cmd/csi/main.go` line 75 at r3](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/55#-N2xfaSL4haw6GPCu6u9:-N31NrsY7iqEJwDmgGiw:b-dqo2s2) ([raw file](https://github.com/vmware/cloud-director-named-disk-csi-driver/blob/3d46f893b0208e4a0ea203a2ca9884aafc69ff92/cmd/csi/main.go#L75)):*
<details><summary><i>Previously, ymo24 wrote…</i></summary><blockquote>

Done.
</blockquote></details>

What is this flag ?
___
*[`pkg/csi/driver.go` line 125 at r3](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/55#-N2xp1kvCGE5erNOSxmO:-N30vFy588XuyLmiaDOs:b4u6zqp) ([raw file](https://github.com/vmware/cloud-director-named-disk-csi-driver/blob/3d46f893b0208e4a0ea203a2ca9884aafc69ff92/pkg/csi/driver.go#L125)):*
<details><summary><i>Previously, ymo24 wrote…</i></summary><blockquote>

Done.
</blockquote></details>



Please ensure we fail CSI if and only if RDE ID is valid and upgrade fails.

If RDE Id is invalid or absent, CSI should never fail.
___
*[`pkg/util/defined_entity_util.go` line 92 at r3](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/55#-N313i-t-OvzE6qYFEzV:-N313HRv8A2WHpsCfyId:bd9kxj2) ([raw file](https://github.com/vmware/cloud-director-named-disk-csi-driver/blob/3d46f893b0208e4a0ea203a2ca9884aafc69ff92/pkg/util/defined_entity_util.go#L92)):*
> ```Go
> }
> 
> func UpgradePVResourceToRDE(statusMap map[string]interface{}, pvDetailList [][]string, rdeId string) (map[string]interface{}, error) {
> ```

Rename to UpgradeStatusMapOfRdeToLatestFormat()
Please add a comment about what this func does - takes a list of pvs(name and id) and adds them to the newer format of the in-memory status map.

At first, I thought this method was persisting to VCD.
___
*[`pkg/util/defined_entity_util.go` line 152 at r3](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/55#-N310dFx5nT_0mZputca:-N310dFx5nT_0mZputcb:blel369) ([raw file](https://github.com/vmware/cloud-director-named-disk-csi-driver/blob/3d46f893b0208e4a0ea203a2ca9884aafc69ff92/pkg/util/defined_entity_util.go#L152)):*
> ```Go
> }
> 
> func addToVCDResourceSet(component string, componentName string, componentVersion string, statusMap map[string]interface{}, vcdResourceSet []vcdsdk.VCDResource) (map[string]interface{}, error) {
> ```

This method should have ideally been in CPI. I think you added this to support the modification of multiple resources at once.
When we have time, we can modify the CPI methods itself to support that.
___
*[`pkg/vcdcsiclient/disks.go` line 699 at r2](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/55#-N2x8ZHo4jZedBFE14lB:-N31M7i444OZTRGjoh6Q:b-dxtw6c) ([raw file](https://github.com/vmware/cloud-director-named-disk-csi-driver/blob/0ea3e132db1eaed22bc3fad2618e0172553c9760/pkg/vcdcsiclient/disks.go#L699)):*
<details><summary><i>Previously, ymo24 wrote…</i></summary><blockquote>

> a. get list of PV
</blockquote></details>

Please add comments 
___
*[`pkg/vcdcsiclient/disks.go` line 695 at r3](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/55#-N31LALu3Z97zQrw2GS5:-N31LALu3Z97zQrw2GS6:b-7b8fja) ([raw file](https://github.com/vmware/cloud-director-named-disk-csi-driver/blob/3d46f893b0208e4a0ea203a2ca9884aafc69ff92/pkg/vcdcsiclient/disks.go#L695)):*
> ```Go
> 			return fmt.Errorf("key 'status' found in the status section of RDE: [%s]", diskManager.ClusterID)
> 		}
> 		statusMap, ok := statusEntry.(map[string]interface{})
> ```

The first step is to add the missing "CSI" section in the RDE. I know you are adding CSI section as part of addToVcdResourceSet,
It would be good to have those methods just patch CSI section instead of entire status section.

It is okay for now. 


<!-- Sent from Reviewable.io -->

2022-05-27 02:53 UTC, Anirudh9794 requested changes
> Reviewed 1 of 4 files at r2, 10 of 10 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/55)* status: all files reviewed, 33 unresolved discussions (waiting on @Anirudh9794, @arunmk, @sahithi, and @ymo24)

___
*[`pkg/csi/driver.go` line 117 at r4](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/55#-N31Viyt9VirBG9Zp3T-:-N31Viyt9VirBG9Zp3T0:b2cmc9t) ([raw file](https://github.com/vmware/cloud-director-named-disk-csi-driver/blob/b6f20cc01bcb2fbefd004e9ad5b013a4a8b6f95d/pkg/csi/driver.go#L117)):*
> ```Go
> 	d.ids = NewIdentityServer(d)
> 	if !upgradeRde {
> 		klog.Infof("Skipping RDE CSI section upgrade as upgradeRde flag is invalid")
> ```


"Skipping RDE CSI section upgrade as upgradeRDE flag is false"
___
*[`pkg/csi/driver.go` line 128 at r4](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/55#-N31iGMMB_u3umjP_eo-:-N31iGMN4WXy6_na8_jk:bqodrl8) ([raw file](https://github.com/vmware/cloud-director-named-disk-csi-driver/blob/b6f20cc01bcb2fbefd004e9ad5b013a4a8b6f95d/pkg/csi/driver.go#L128)):*
> ```Go
> 		return nil
> 	}
> 	if vcdsdk.IsCAPVCDEntityType(diskManager.ClusterID) {
> ```

I think this check seems better than the check for native entity type.
We can remove the check for native entity type as these are redundant.
___
*[`pkg/util/defined_entity_util.go` line 152 at r3](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/55#-N310dFx5nT_0mZputca:-N32PFbn5vncMvFU2sXt:b32v57) ([raw file](https://github.com/vmware/cloud-director-named-disk-csi-driver/blob/3d46f893b0208e4a0ea203a2ca9884aafc69ff92/pkg/util/defined_entity_util.go#L152)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

This method should have ideally been in CPI. I think you added this to support the modification of multiple resources at once.
When we have time, we can modify the CPI methods itself to support that.
</blockquote></details>

+1
___
*[`pkg/util/defined_entity_util.go` line 88 at r4](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/55#-N32KiKB1oM0hKhuDPHY:-N32KiKB1oM0hKhuDPHZ:bpu6yjv) ([raw file](https://github.com/vmware/cloud-director-named-disk-csi-driver/blob/b6f20cc01bcb2fbefd004e9ad5b013a4a8b6f95d/pkg/util/defined_entity_util.go#L88)):*
> ```Go
> }
> 
> func UpgradePVResourceToRDE(statusMap map[string]interface{}, pvDetailList [][]string, rdeId string) (map[string]interface{}, error) {
> ```

`pvDetailList` param can be of type `[]vcdsdk.VCDResource`
___
*[`pkg/util/defined_entity_util.go` line 90 at r4](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/55#-N32KT8V7dMvO3qWwCb9:-N32KT8V7dMvO3qWwCbA:b-i2hduk) ([raw file](https://github.com/vmware/cloud-director-named-disk-csi-driver/blob/b6f20cc01bcb2fbefd004e9ad5b013a4a8b6f95d/pkg/util/defined_entity_util.go#L90)):*
> ```Go
> func UpgradePVResourceToRDE(statusMap map[string]interface{}, pvDetailList [][]string, rdeId string) (map[string]interface{}, error) {
> 	if pvDetailList == nil || len(pvDetailList) == 0 || len(pvDetailList[0]) != PVDetailsNum {
> 		return nil, fmt.Errorf("error occurred when validating pv details list in RDE [%s]", rdeId)
> ```

CSI running before the upgrade may not be used to create any persistent volumes. So it doesn't make sense to return an error here if `pvDetailList` is empty
___
*[`pkg/util/defined_entity_util.go` line 108 at r4](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/55#-N32GVki9Y6d2PsNMDqj:-N32GVki9Y6d2PsNMDqk:baro1gn) ([raw file](https://github.com/vmware/cloud-director-named-disk-csi-driver/blob/b6f20cc01bcb2fbefd004e9ad5b013a4a8b6f95d/pkg/util/defined_entity_util.go#L108)):*
> ```Go
> }
> 
> func GetOldPVsFromRDE(statusMap map[string]interface{}, rdeId string) ([]string, error) {
> ```

We don't need an error here. We can just log the error if any and return an empty slice.

We should not fail CSI controller startup if "persistentVolumes" cannot be found in the old RDE/ if the value for "persistentVolumes" is an invalid one.
___
*[`pkg/util/defined_entity_util.go` line 166 at r4](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/55#-N32Ph0Q9g6eYl5WUWEc:-N32Ph0Q9g6eYl5WUWEd:b-6g87kf) ([raw file](https://github.com/vmware/cloud-director-named-disk-csi-driver/blob/b6f20cc01bcb2fbefd004e9ad5b013a4a8b6f95d/pkg/util/defined_entity_util.go#L166)):*
> ```Go
> 		return nil, fmt.Errorf("failed to convert the status belonging to component [%s] to map[string]interface{}", component)
> 	}
> ```

please add version and name to component map at this line too.
___
*[`pkg/util/defined_entity_util.go` line 172 at r4](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/55#-N32NwSwAlMKcHFT5KIR:-N32NwSwAlMKcHFT5KIS:b-wiakx1) ([raw file](https://github.com/vmware/cloud-director-named-disk-csi-driver/blob/b6f20cc01bcb2fbefd004e9ad5b013a4a8b6f95d/pkg/util/defined_entity_util.go#L172)):*
> ```Go
> 	}
> 
> 	if componentStatus.VCDResourceSet == nil || len(componentStatus.VCDResourceSet) == 0 {
> ```

I think len(componentStatus.VCDResourceSet) will give 0.
___
*[`pkg/vcdcsiclient/disks.go` line 214 at r4](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/55#-N32Io4y3baIPaVjxB6K:-N32Io4y3baIPaVjxB6L:b-10u54g) ([raw file](https://github.com/vmware/cloud-director-named-disk-csi-driver/blob/b6f20cc01bcb2fbefd004e9ad5b013a4a8b6f95d/pkg/vcdcsiclient/disks.go#L214)):*
> ```Go
> 		err := diskManager.VCDClient.VDC.Refresh()
> 		if err != nil {
> 			return nil, fmt.Errorf("error when refreshing by disk id %s, [%v]", diskId, err)
> ```

"error refreshing VDC client while getting disk by id [diskId]: [error]"
___
*[`pkg/vcdcsiclient/disks.go` line 694 at r4](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/55#-N32AkzxCYB84bPVpA7W:-N32AkzxCYB84bPVpA7X:bozybfz) ([raw file](https://github.com/vmware/cloud-director-named-disk-csi-driver/blob/b6f20cc01bcb2fbefd004e9ad5b013a4a8b6f95d/pkg/vcdcsiclient/disks.go#L694)):*
> ```Go
> 		statusEntry, ok := rde.Entity["status"]
> 		if !ok {
> 			return fmt.Errorf("key 'status' found in the status section of RDE: [%s]", diskManager.ClusterID)
> ```

I think we should not return an error here. Instead, just add a log statement -
"RDE [rdeID] is missing "status" key; skipping upgrade of CPI section in RDE status"
___
*[`pkg/vcdcsiclient/disks.go` line 701 at r4](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/55#-N32Hgk08WA_lSd2JmPi:-N32Hgk08WA_lSd2JmPj:b-8ahrgg) ([raw file](https://github.com/vmware/cloud-director-named-disk-csi-driver/blob/b6f20cc01bcb2fbefd004e9ad5b013a4a8b6f95d/pkg/vcdcsiclient/disks.go#L701)):*
> ```Go
> 		}
> 		oldPvs, err := util.GetOldPVsFromRDE(statusMap, diskManager.ClusterID)
> 		if err != nil {
> ```

no need to fail CSI startup if "persistentVolumes" is not present in the old RDE.
___
*[`pkg/vcdcsiclient/disks.go` line 707 at r4](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/55#-N32LwWQCwvYX2BvaxM2:-N32LwWQCwvYX2BvaxM3:b-rm1lm9) ([raw file](https://github.com/vmware/cloud-director-named-disk-csi-driver/blob/b6f20cc01bcb2fbefd004e9ad5b013a4a8b6f95d/pkg/vcdcsiclient/disks.go#L707)):*
> ```Go
> 		updatedMap := statusMap
> 		if len(oldPvs) > 0 {
> 			PVDetailList := make([][]string, len(oldPvs))
> ```

Why can we not make use of `[]vcdsdk.VCDResource` over here?
___
*[`pkg/vcdcsiclient/disks.go` line 713 at r4](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/55#-N32JjIPCFIWXMllRw4e:-N32JjIQ446wRxTKdjFA:bwtziqj) ([raw file](https://github.com/vmware/cloud-director-named-disk-csi-driver/blob/b6f20cc01bcb2fbefd004e9ad5b013a4a8b6f95d/pkg/vcdcsiclient/disks.go#L713)):*
> ```Go
> 				if err != nil {
> 					// Todo: update csi.errors => disk query failed
> 					klog.Infof("error when conducting disk query with id [%s]", oldPVId)
 [...]

2022-05-27 17:44 UTC, ymo24 reviewed
> *[Reviewable](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/55)* status: all files reviewed, 31 unresolved discussions (waiting on @Anirudh9794, @arunmk, and @sahithi)

___
*[`cmd/csi/main.go` line 75 at r3](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/55#-N2xfaSL4haw6GPCu6u9:-N35Wu7P-75M00UP6uB3:bscy7k5) ([raw file](https://github.com/vmware/cloud-director-named-disk-csi-driver/blob/3d46f893b0208e4a0ea203a2ca9884aafc69ff92/cmd/csi/main.go#L75)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

What is this flag ?
</blockquote></details>

to distinguish controller and node-plugin. We want RDE Upgrade only happen once. Otherwise, that would cause race condition.
___
*[`pkg/csi/driver.go` line 125 at r3](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/55#-N2xp1kvCGE5erNOSxmO:-N337bywCMbyAALmHMrY:b-896fix) ([raw file](https://github.com/vmware/cloud-director-named-disk-csi-driver/blob/3d46f893b0208e4a0ea203a2ca9884aafc69ff92/pkg/csi/driver.go#L125)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>



Please ensure we fail CSI if and only if RDE ID is valid and upgrade fails.

If RDE Id is invalid or absent, CSI should never fail.
</blockquote></details>

Done.
___
*[`pkg/csi/driver.go` line 117 at r4](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/55#-N31Viyt9VirBG9Zp3T-:-N337FoRCSUfiivbZSXn:b-896fix) ([raw file](https://github.com/vmware/cloud-director-named-disk-csi-driver/blob/b6f20cc01bcb2fbefd004e9ad5b013a4a8b6f95d/pkg/csi/driver.go#L117)):*
<details><summary><i>Previously, Anirudh9794 wrote…</i></summary><blockquote>

"Skipping RDE CSI section upgrade as upgradeRDE flag is false"
</blockquote></details>

Done.
___
*[`pkg/csi/driver.go` line 128 at r4](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/55#-N31iGMMB_u3umjP_eo-:-N35TgPR8L5DpZoxbhjA:b-896fix) ([raw file](https://github.com/vmware/cloud-director-named-disk-csi-driver/blob/b6f20cc01bcb2fbefd004e9ad5b013a4a8b6f95d/pkg/csi/driver.go#L128)):*
<details><summary><i>Previously, Anirudh9794 wrote…</i></summary><blockquote>

I think this check seems better than the check for native entity type.
We can remove the check for native entity type as these are redundant.
</blockquote></details>

Done.
___
*[`pkg/util/defined_entity_util.go` line 92 at r3](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/55#-N313i-t-OvzE6qYFEzV:-N33BxwdB263_BNv24i2:b-896fix) ([raw file](https://github.com/vmware/cloud-director-named-disk-csi-driver/blob/3d46f893b0208e4a0ea203a2ca9884aafc69ff92/pkg/util/defined_entity_util.go#L92)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

Rename to UpgradeStatusMapOfRdeToLatestFormat()
Please add a comment about what this func does - takes a list of pvs(name and id) and adds them to the newer format of the in-memory status map.

At first, I thought this method was persisting to VCD.
</blockquote></details>

Done.
___
*[`pkg/util/defined_entity_util.go` line 152 at r3](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/55#-N310dFx5nT_0mZputca:-N33DRsB8UcZh6TuDw1m:b-896fix) ([raw file](https://github.com/vmware/cloud-director-named-disk-csi-driver/blob/3d46f893b0208e4a0ea203a2ca9884aafc69ff92/pkg/util/defined_entity_util.go#L152)):*
<details><summary><i>Previously, Anirudh9794 wrote…</i></summary><blockquote>

+1
</blockquote></details>

Done.
___
*[`pkg/util/defined_entity_util.go` line 88 at r4](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/55#-N32KiKB1oM0hKhuDPHY:-N33Ar_t4G5Xw9HAKouZ:b-896fix) ([raw file](https://github.com/vmware/cloud-director-named-disk-csi-driver/blob/b6f20cc01bcb2fbefd004e9ad5b013a4a8b6f95d/pkg/util/defined_entity_util.go#L88)):*
<details><summary><i>Previously, Anirudh9794 wrote…</i></summary><blockquote>

`pvDetailList` param can be of type `[]vcdsdk.VCDResource`
</blockquote></details>

Done.
___
*[`pkg/util/defined_entity_util.go` line 90 at r4](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/55#-N32KT8V7dMvO3qWwCb9:-N33AqClDme79IqY7GOh:b-896fix) ([raw file](https://github.com/vmware/cloud-director-named-disk-csi-driver/blob/b6f20cc01bcb2fbefd004e9ad5b013a4a8b6f95d/pkg/util/defined_entity_util.go#L90)):*
<details><summary><i>Previously, Anirudh9794 wrote…</i></summary><blockquote>

CSI running before the upgrade may not be used to create any persistent volumes. So it doesn't make sense to return an error here if `pvDetailList` is empty
</blockquote></details>

Done.
___
*[`pkg/util/defined_entity_util.go` line 108 at r4](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/55#-N32GVki9Y6d2PsNMDqj:-N33DNsm1DHDRM5n_jay:b-896fix) ([raw file](https://github.com/vmware/cloud-director-named-disk-csi-driver/blob/b6f20cc01bcb2fbefd004e9ad5b013a4a8b6f95d/pkg/util/defined_entity_util.go#L108)):*
<details><summary><i>Previously, Anirudh9794 wrote…</i></summary><blockquote>

We don't need an error here. We can just log the error if any and return an empty slice.

We should not fail CSI controller startup if "persistentVolumes" cannot be found in the old RDE/ if the value for "persistentVolumes" is an invalid one.
</blockquote></details>

Done.
___
*[`pkg/util/defined_entity_util.go` line 166 at r4](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/55#-N32Ph0Q9g6eYl5WUWEc:-N33GP806CUdwwNs5Vjk:b-896fix) ([raw file](https://github.com/vmware/cloud-director-named-disk-csi-driver/blob/b6f20cc01bcb2fbefd004e9ad5b013a4a8b6f95d/pkg/util/defined_entity_util.go#L166)):*
<details><summary><i>Previously, Anirudh9794 wrote…</i></summary><blockquote>

please add version and name to component map at this line too.
</blockquote></details>

Done.
___
*[`pkg/util/defined_entity_util.go` line 172 at r4](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/55#-N32NwSwAlMKcHFT5KIR:-N33FMxiAJvnGTfgo9dQ:bqhqtvc) ([raw file](https://github.com/vmware/cloud-director-named-disk-csi-driver/blob/b6f20cc01bcb2fbefd004e9ad5b013a4a8b6f95d/pkg/util/defined_entity_util.go#L172)):*
<details><summary><i>Previously, Anirudh9794 wrote…</i></summary><blockquote>

I think len(componentStatus.VCDResourceSet) will give 0.
</blockquote></details>

Two cases: 1. RDE doesn't have the VCDResourceSet like you said, the length will give 0. 
2. RDE has both vcdResourceSet section and persistentVolumes section at the same time. In this case, we should probably keep the details of original PV resource set and upgrade PV in persistentVolumes section to resourceSet section.
___
*[`pkg/vcdcsiclient/disks.go` line 695 at r3](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/55#-N31LALu3Z97zQrw2GS5:-N35ZPqp20WNNEh09-LC:bc02wc4) ([raw file](https://github.com/vmware/cloud-director-named-disk-csi-driver/blob/3d46f893b0208e4a0ea203a2ca9884aafc69ff92/pkg/vcdcsiclient/disks.go#L695)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

The first step is to add the missing "CSI" section in the RDE. I know you are adding CSI section as part of addToVcdResourceSet,
It would be good to have those methods just patch CSI section instead of entire status section.

It is okay for now. 

</blockquote></details>

Thanks Sahithi
___
*[`pkg/vcdcsiclient/disks.go` line 214 at r4](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/55#-N32Io4y3baIPaVjxB6K:-N33GUgbCRnMA0RmcZvT:b-68t4zw) ([raw file](https://github.com/vmware/cloud-director-named-disk-csi-driver/blob/b6f20cc01bcb2fbefd004e9ad5b013a4a8b6f95d/pkg/vcdcsiclient/disks.go#L214)):*
<details><summary><i>Previously, Anirudh9794 wrote…</i></summary><blockquote>

"error refreshing VDC client while getting disk by id [diskId]: [error]"
</blockquote></details>

Sounds much b [...]

2022-05-29 17:05 UTC, Anirudh9794 approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>
Please also make sure that restarting CSI pod restarts won't affect CSI start-up.

> Reviewed 2 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/55#-:-N3FlM830nsa3LgUR5cC:ba85hqc)* status: 10 of 11 files reviewed, 23 unresolved discussions (waiting on @Anirudh9794, @arunmk, @sahithi, and @ymo24)

___
*[`pkg/vcdcsiclient/disks.go` line 701 at r4](https://reviewable.io/reviews/vmware/cloud-director-named-disk-csi-driver/55#-N32Hgk08WA_lSd2JmPi:-N3Fk5kO7NVKQX3izF4_:b-j57cyt) ([raw file](https://github.com/vmware/cloud-director-named-disk-csi-driver/blob/b6f20cc01bcb2fbefd004e9ad5b013a4a8b6f95d/pkg/vcdcsiclient/disks.go#L701)):*
<details><summary><i>Previously, ymo24 wrote…</i></summary><blockquote>

We only fail CSI startup when the interface under `persistentVolumes` section can't be converted
</blockquote></details>

I feel like we should not fail when the `persistentVolumes` section can't be converted too. 
Maybe this needs more discussion. Because someone can add a persistentVolumes section in the RDE with incorrect format, which will cause CSI to not start up


<!-- Sent from Reviewable.io -->

2022-06-01 03:51 UTC, merged